---
- name: Converge
  hosts: all
  roles:
    - role: rbicker.nextcloud
  vars:
    nextcloud_admin_user: admin
    nextcloud_admin_pw: test
    nextcloud_use_https: no
    nextcloud_domain: localhost
    nextcloud_upgrade: yes
    nextcloud_version: latest
